services:
  app:
    image: epickid976/budgetapi:latest
    container_name: budgetapi
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  db:
    image: postgres:16-alpine
    container_name: budgetapi-db
    restart: always
    environment:
      POSTGRES_DB: budgetapi
      POSTGRES_USER: budgetuser
      POSTGRES_PASSWORD: "0430906"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: